import { QUIZZES } from './seeds.mjs';

const DEFAULT_CLASSES = [
  {id:'b3-tronc-commun',name:'B3 Tronc commun',level:'Bachelor 3',courses:['Outils collaboratifs','Gestion de projet','Soft skills'],revision:0},
  {id:'b3-cdui',name:'B3 CDUI',level:'Bachelor 3',courses:[],revision:0},
  {id:'m2-marketing',name:'M2 Marketing & Communication',level:'Mastère 2',courses:['Acquisition digitale'],revision:0}
];
const copy = x => structuredClone(x);
const clean = (v,max=200) => String(v??'').trim().slice(0,max);
const validId = v => /^[a-zA-Z0-9_-]{1,80}$/.test(v);
const now = () => Date.now();
const reply = (data,status=200) => Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const fail = (message,status=400) => { throw Object.assign(new Error(message),{status}); };
const correctArray = q => Array.isArray(q.correct)?q.correct:(Number.isInteger(q.correct)?[q.correct]:[]);
const equal = (a,b) => { const aa=Array.isArray(a)?a:[a],bb=Array.isArray(b)?b:[b]; return aa.length===bb.length&&aa.every((v,i)=>v===bb[i]); };
const skillLabel = n => n>=80?'Maîtrisé':n>=60?'À consolider':'À reprendre';
function quizReady(q){return q.questions.length>0&&q.questions.every(x=>correctArray(x).length>0);}
function normalizedQuiz(input,id,revision){
  const title=clean(input.title,160); if(!title)fail('Donne un titre à ton quiz.');
  if(!Array.isArray(input.questions)||!input.questions.length||input.questions.length>200)fail('Un quiz doit contenir entre 1 et 200 questions.');
  const questions=input.questions.map((x,i)=>{
    const question=clean(x.question,2000); if(!question)fail(`Question ${i+1} : énoncé manquant.`);
    if(!Array.isArray(x.options)||x.options.length<2||x.options.length>6)fail(`Question ${i+1} : prévois entre 2 et 6 choix.`);
    const options=x.options.map(o=>clean(o,1500));if(options.some(o=>!o))fail(`Question ${i+1} : un choix est vide.`);
    const c=correctArray(x);if(c.some(n=>!Number.isInteger(n)||n<0||n>=options.length))fail(`Question ${i+1} : bonne réponse invalide.`);
    const correct=[...new Set(c)].sort((a,b)=>a-b),multi=x.type==='multi'||correct.length>1;
    return {id:'q'+(i+1),question,options,correct:multi?correct:(correct[0]??null),type:multi?'multi':'single',theme:clean(x.theme,120)||'Général',competency:clean(x.competency,120)||clean(x.theme,120)||'Général',explanation:clean(x.explanation,2500)};
  });
  const q={id,title,shortTitle:title,description:clean(input.description,3000),context:clean(input.context,6000),classId:clean(input.classId,80)||null,course:clean(input.course,160),level:clean(input.level,160),questions,revision,updatedAt:now(),builtin:false};
  q.status=quizReady(q)?'ready':'draft';return q;
}
const code = () => { const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>chars[n%chars.length]).join(''); };
function fresh(q,klass=null){return {quizId:q.id,quizSnapshot:copy(q),classInfo:klass?{id:klass.id,name:klass.name,level:klass.level}:null,course:q.course||'',status:'waiting',phase:'quiz',current:0,reveal:false,locked:false,paused:false,pauseRemainingMs:null,startedAt:null,questionStartedAt:null,deadlineAt:null,defaultDurationSec:0,sessionCode:code(),showLeaderboard:false,speedBonusEnabled:false,version:1,createdAt:now()};}
const quizOf=s=>s.quizSnapshot||QUIZZES[s.quizId];
const activeQuestion=s=>s.phase==='challenge'?quizOf(s).challenge:s.phase==='surprise'?quizOf(s).surprise?.question:quizOf(s).questions[s.current];
const activeKey=s=>s.phase==='quiz'?'q'+s.current:s.phase;
const expired=s=>!!(s.deadlineAt&&!s.paused&&now()>=s.deadlineAt);
const remaining=s=>s.paused&&s.pauseRemainingMs!=null?Math.ceil(s.pauseRemainingMs/1000):s.deadlineAt?Math.max(0,Math.ceil((s.deadlineAt-now())/1000)):null;
function open(s){s.reveal=false;s.locked=false;s.paused=false;s.pauseRemainingMs=null;s.questionPausedAt=null;s.pausedDurationMs=0;s.questionStartedAt=now();s.deadlineAt=s.defaultDurationSec?now()+s.defaultDurationSec*1000:null;}
function safeQuestion(q,reveal){if(!q)return null;const x={id:q.id,question:q.question,options:q.options,type:q.type||'single',theme:q.theme,competency:q.competency};if(reveal){x.correct=q.correct;x.explanation=q.explanation;}return x;}
function publicState(s){const q=quizOf(s);return {status:s.status,phase:s.phase,current:s.current,reveal:s.reveal,locked:s.locked||expired(s),paused:s.paused,remainingSec:remaining(s),questionKey:s.status==='active'?activeKey(s):null,question:s.status==='active'?safeQuestion(activeQuestion(s),s.reveal):null,specialCard:s.phase==='surprise'&&q.surprise?{title:q.surprise.title,body:q.surprise.body}:null,quiz:{id:q.id,title:q.title,shortTitle:q.shortTitle,level:q.level,description:q.description,context:q.context||'',contextHtml:q.builtin===false?'':q.contextHtml||'',totalQuestions:q.questions.length,hasChallenge:!!q.challenge,hasSurprise:!!q.surprise},classInfo:s.classInfo||null,course:s.course||'',sessionCode:s.sessionCode,defaultDurationSec:s.defaultDurationSec,showLeaderboard:s.showLeaderboard,speedBonusEnabled:s.speedBonusEnabled,version:s.version};}
function points(s,q,a){if(!a||!equal(a.answer,q.correct))return {correct:false,bonus:0,total:0};const bonus=s.speedBonusEnabled&&a.durationSec>0?Math.floor(250*Math.max(0,1-a.elapsedMs/(a.durationSec*1000))):0;return {correct:true,bonus,total:1000+bonus};}
function metric(q,rows,total){const counts=q.options.map(()=>0);rows.forEach(a=>(Array.isArray(a.answer)?a.answer:[a.answer]).forEach(n=>counts[n]++));const good=rows.filter(a=>equal(a.answer,q.correct)).length;return {id:q.id,theme:q.theme,competency:q.competency,type:q.type||'single',counts,responses:rows.length,notAnswered:Math.max(0,total-rows.length),correctCount:good,successRate:rows.length?Math.round(good*100/rows.length):0,avgResponseSec:rows.length?Math.round(rows.reduce((v,a)=>v+a.elapsedMs,0)/rows.length/100)/10:0};}
function score(s,answers){const q=quizOf(s),skills={};let correctCount=0,total=0,bonus=0;const mine={};q.questions.forEach((x,i)=>{const a=answers.find(a=>a.key==='q'+i);skills[x.competency]||={correct:0,total:0};skills[x.competency].total++;if(a){mine['q'+i]=a.answer;const p=points(s,x,a);if(p.correct){correctCount++;skills[x.competency].correct++;}total+=p.total;bonus+=p.bonus;}});const skillRates=Object.fromEntries(Object.entries(skills).map(([k,v])=>[k,Math.round(v.correct*100/v.total)]));return {points:total,score:total,basePoints:correctCount*1000,bonus,correctCount,total:q.questions.length,maxBasePoints:q.questions.length*1000,percent:Math.round(correctCount*100/q.questions.length),answers:mine,skillRates,skills:Object.entries(skillRates).map(([name,rate])=>({name,rate,status:skillLabel(rate)}))};}

export function createHandler({getStore,teacherPin}){
  const db=()=>getStore(),read=key=>db().get(key,{type:'json'}),write=(key,value)=>db().setJSON(key,value);
  async function readRecord(key){const found=await db().getWithMetadata(key,{type:'json'});if(!found||found.etag)return found;for(let attempt=0;attempt<3;attempt++){const before=(await db().list({prefix:key})).blobs.find(b=>b.key===key)?.etag;const current=await db().getWithMetadata(key,{type:'json'});const after=(await db().list({prefix:key})).blobs.find(b=>b.key===key)?.etag;if(!current&&!after)return null;if(current&&before&&before===after)return {...current,etag:before};}fail('La sauvegarde vient de changer. Réessaie dans quelques instants.',409);}
  async function list(prefix){const {blobs}=await db().list({prefix});return (await Promise.all(blobs.map(b=>read(b.key)))).filter(Boolean);}
  async function classes(){const custom=await list('classes/'),base=DEFAULT_CLASSES.map(copy);return [...base.filter(x=>!custom.some(y=>y.id===x.id)),...custom].sort((a,b)=>a.name.localeCompare(b.name));}
  async function quizzes(){const custom=await list('quizzes/');return [...Object.values(QUIZZES).map(q=>({...copy(q),classId:'m2-marketing',course:'Acquisition digitale',builtin:true,status:'ready',revision:0})),...custom];}
  async function getQuiz(id){const builtin=Object.hasOwn(QUIZZES,id)?QUIZZES[id]:null;return builtin?{...copy(builtin),classId:'m2-marketing',course:'Acquisition digitale',builtin:true,status:'ready',revision:0}:validId(id)?read('quizzes/'+id):null;}
  async function saveItem(prefix,id,value,expectedRevision){const key=prefix+id,record=await readRecord(key);if(record&&record.data.revision!==expectedRevision)fail('Une autre version a été enregistrée. Recharge avant de réessayer.',409);const result=await db().setJSON(key,value,record?{onlyIfMatch:record.etag}:{onlyIfNew:true});if(!result.modified)fail('Une autre version a été enregistrée. Recharge avant de réessayer.',409);}
  async function save(s){s.version++;const result=await db().setJSON('session-control/'+s.sessionCode,s,s._etag?{onlyIfMatch:s._etag}:{onlyIfNew:true});if(!result.modified)fail('La session vient de changer. Attends son actualisation, puis réessaie.',409);Object.defineProperty(s,'_etag',{value:result.etag,writable:true,configurable:true,enumerable:false});return s;}
  async function createSession(q,klass){const s=fresh(q,klass);for(let n=0;n<8;n++){if(!await read('session-control/'+s.sessionCode))break;s.sessionCode=code();}if(await read('session-control/'+s.sessionCode))fail('Réessaie la création de la session.',503);await save(s);await write('control',{activeSessionCode:s.sessionCode});return s;}
  async function load(wanted){const pointer=await read('control');const sid=wanted||pointer?.activeSessionCode||pointer?.sessionCode;if(sid){if(!/^[A-Z0-9]{6}$/.test(sid))fail('Code de session invalide.',404);const record=await readRecord('session-control/'+sid);let s=record?.data;if(s)Object.defineProperty(s,'_etag',{value:record.etag,writable:true,configurable:true,enumerable:false});if(!s&&pointer?.sessionCode===sid&&QUIZZES[pointer.quizId]){s={...pointer,quizSnapshot:copy(QUIZZES[pointer.quizId])};await save(s);}if(s)return s;if(wanted)fail('Cette session est introuvable. Vérifie le code avec ton enseignant.',404);}return createSession((await getQuiz('diagnostic')),(await classes()).find(x=>x.id==='m2-marketing'));}
  const pPrefix=s=>'sessions/'+s.sessionCode+'/participants/',aPrefix=s=>'sessions/'+s.sessionCode+'/answers/';
  async function student(s,id){if(!validId(id))return null;const p=await read(pPrefix(s)+id);if(!p)return null;const keys=s.status==='finished'?quizOf(s).questions.map((_,i)=>'q'+i):[activeKey(s)];const mine=(await Promise.all(keys.map(key=>read(aPrefix(s)+key+'/'+id)))).filter(Boolean),a=mine.find(a=>a.key===activeKey(s));let leaderboard=null;if(s.showLeaderboard&&s.status==='finished'){const t=await teacher(s,false);leaderboard=t.participants.slice(0,10).map((x,i)=>({rank:i+1,name:x.name,percent:x.percent,score:x.score}));}return {...publicState(s),participant:{id:p.id,name:p.name},answered:!!a,participantAnswer:a?.answer??null,participantCorrect:s.reveal&&a?equal(a.answer,activeQuestion(s).correct):null,score:s.status==='finished'?score(s,mine):null,leaderboard};}
  async function teacher(s,withQuizzes=true){const [ps,answers]=await Promise.all([list(pPrefix(s)),list(aPrefix(s))]),q=quizOf(s);const people=ps.map(p=>({...p,...score(s,answers.filter(a=>a.participantId===p.id))})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name));const metrics=q.questions.map((x,i)=>metric(x,answers.filter(a=>a.key==='q'+i),ps.length));const aq=activeQuestion(s);const skills=[...new Set(q.questions.map(x=>x.competency))].map(name=>{const m=metrics.filter(x=>x.competency===name),responses=m.reduce((v,x)=>v+x.responses,0),rate=responses?Math.round(m.reduce((v,x)=>v+x.correctCount,0)*100/responses):0;return {name,rate,responses,status:responses?skillLabel(rate):'Non mesuré'};});const measured=metrics.filter(m=>m.responses),sorted=people.map(p=>p.percent).sort((a,b)=>a-b);const best=[...measured].sort((a,b)=>b.successRate-a.successRate)[0],worst=[...measured].sort((a,b)=>a.successRate-b.successRate)[0];return {...publicState(s),quizFull:q,currentMetric:aq?metric(aq,answers.filter(a=>a.key===activeKey(s)),ps.length):null,metrics,participants:people,participantCount:ps.length,skills,summary:{scoreMean:people.length?Math.round(people.reduce((v,p)=>v+p.percent,0)/people.length):0,median:sorted.length?Math.round((sorted[Math.floor((sorted.length-1)/2)]+sorted[Math.floor(sorted.length/2)])/2):0,bestScore:people[0]?.percent||0,successGlobal:measured.length?Math.round(measured.reduce((v,m)=>v+m.successRate,0)/measured.length):0,bestQuestion:best?{theme:best.theme,rate:best.successRate}:null,worstQuestion:worst?{theme:worst.theme,rate:worst.successRate}:null},availableQuizzes:withQuizzes?(await quizzes()).filter(quizReady).map(x=>({id:x.id,title:x.title,shortTitle:x.shortTitle,totalQuestions:x.questions.length})):[]};}
  function requireTeacher(req){const configured=teacherPin();if(!configured)fail('Accès enseignant non configuré sur le serveur.',503);if(req.headers.get('x-teacher-pin')!==configured)fail('PIN enseignant incorrect.',401);}
  async function sessionSummary(s){const t=await teacher(s,false);return {sessionCode:s.sessionCode,quizId:s.quizId,title:quizOf(s).title,classInfo:s.classInfo,status:s.status,createdAt:s.createdAt,participantCount:t.participantCount,scoreMean:t.summary.scoreMean};}
  return async req=>{
    try{
      const u=new URL(req.url),action=u.searchParams.get('action')||'state';if(!['GET','POST'].includes(req.method))return reply({error:'Méthode non autorisée.'},405);
      const teacherAction=!['state','join','student','answer'].includes(action);if(teacherAction)requireTeacher(req);
      let body={};if(req.method==='POST'){const raw=await req.text();if(raw.length>1800000)fail('Le quiz est trop volumineux.',413);try{body=JSON.parse(raw||'{}');}catch{fail('Données invalides.');}}
      if(action==='library'&&req.method==='GET'){const [cs,qs,ss]=await Promise.all([classes(),quizzes(),list('session-control/')]);return reply({classes:cs,quizzes:qs.map(q=>({id:q.id,title:q.title,classId:q.classId,course:q.course,builtin:q.builtin,status:q.status,questionCount:q.questions.length,revision:q.revision,updatedAt:q.updatedAt})),sessions:await Promise.all(ss.sort((a,b)=>b.createdAt-a.createdAt).slice(0,60).map(sessionSummary))});}
      if(action==='quiz'&&req.method==='GET'){const q=await getQuiz(u.searchParams.get('id'));return q?reply(q):reply({error:'Quiz introuvable.'},404);}
      if(action==='saveClass'&&req.method==='POST'){const x=body.classData||{},all=await classes(),old=x.id?all.find(c=>c.id===x.id):null;if(x.id&&!old)fail('Classe introuvable.',404);if(old&&Number(x.revision)!==old.revision)fail('Cette classe a été modifiée. Recharge-la avant de réessayer.',409);const name=clean(x.name,160);if(!name)fail('Le nom de la classe est obligatoire.');if(all.some(c=>c.id!==x.id&&c.name.toLocaleLowerCase()===name.toLocaleLowerCase()))fail('Une classe porte déjà ce nom.');const c={id:old?.id||crypto.randomUUID(),name,level:clean(x.level,100),courses:[...new Set((Array.isArray(x.courses)?x.courses:[]).map(v=>clean(v,160)).filter(Boolean))].slice(0,30),revision:(old?.revision||0)+1,updatedAt:now()};await saveItem('classes/',c.id,c,old?.revision);return reply(c);}
      if(action==='saveQuiz'&&req.method==='POST'){const x=body.quiz||{},old=x.id?await getQuiz(x.id):null;if(x.id&&!old)fail('Quiz introuvable.',404);if(old?.builtin)fail('Duplique ce quiz pour le personnaliser.');if(old&&Number(x.revision)!==old.revision)fail('Ce quiz a été modifié. Recharge-le avant de réessayer.',409);const q=normalizedQuiz(x,old?.id||crypto.randomUUID(),(old?.revision||0)+1);if(q.classId&&!(await classes()).some(c=>c.id===q.classId))fail('Classe introuvable.');await saveItem('quizzes/',q.id,q,old?.revision);return reply(q);}
      if(['createSession','selectQuiz'].includes(action)&&req.method==='POST'){const q=await getQuiz(clean(body.quizId,80));if(!q)fail('Quiz introuvable.',404);if(!quizReady(q))fail('Définis les bonnes réponses de toutes les questions avant de lancer ce quiz.');const classId=clean(body.classId,80)||q.classId||null;const c=classId?(await classes()).find(x=>x.id===classId):null;if(classId&&!c)fail('Classe introuvable.');return reply(await teacher(await createSession(q,c)));}
      let requested=clean(u.searchParams.get('session')||body.sessionCode,8).toUpperCase();let s=await load(requested);
      if(req.method==='GET'){if(action==='teacher')return reply(await teacher(s));if(action==='student'){const p=await student(s,u.searchParams.get('id')||'');return p?reply(p):reply({error:'Participant inconnu dans cette session.'},404);}if(action==='state')return reply(publicState(s));fail('Action inconnue.');}
      if(action==='join'){if(s.status==='finished')fail('Cette session est terminée.',409);const name=clean(body.name,40);if(!name)fail('Saisis ton prénom.');const p={id:crypto.randomUUID(),name,joinedAt:now()};await write(pPrefix(s)+p.id,p);return reply({id:p.id,name,state:await student(s,p.id)});}
      if(action==='answer'){const id=clean(body.id,80);if(!validId(id)||!await read(pPrefix(s)+id))fail('Participant inconnu.',404);if(s.status!=='active'||s.paused||s.reveal||s.locked||expired(s))fail('La question est fermée.',409);const q=activeQuestion(s),key=activeKey(s);if(!q||body.key!==key)fail('La question a changé.',409);let answer;if(q.type==='multi'){if(!Array.isArray(body.answer)||!body.answer.length||body.answer.some(n=>!Number.isInteger(n)||n<0||n>=q.options.length))fail('Réponse invalide.');answer=[...new Set(body.answer)].sort((a,b)=>a-b);}else{answer=body.answer;if(!Number.isInteger(answer)||answer<0||answer>=q.options.length)fail('Réponse invalide.');}const path=aPrefix(s)+key+'/'+id;if(await read(path))fail('Ta réponse est déjà enregistrée.',409);const result=await db().setJSON(path,{participantId:id,key,questionId:q.id,answer,elapsedMs:Math.max(0,now()-s.questionStartedAt-(s.pausedDurationMs||0)),durationSec:s.defaultDurationSec,at:now()},{onlyIfNew:true});if(!result.modified)fail('Ta réponse est déjà enregistrée.',409);return reply({saved:true});}
      if(action==='newSession'||action==='reset')return reply(await teacher(await createSession(quizOf(s),s.classInfo)));
      if(action==='start'){if(s.status!=='waiting')fail('Cette session a déjà démarré. Crée une nouvelle session pour recommencer.',409);s.status='active';s.phase='quiz';s.current=0;s.startedAt=now();open(s);}
      else if(action==='settings'){if(s.status!=='waiting')fail('Configure les paramètres avant de démarrer la session.',409);const n=Number(body.defaultDurationSec??s.defaultDurationSec);if(!Number.isInteger(n)||(n!==0&&(n<5||n>600)))fail('Choisis une durée entre 5 et 600 secondes, ou 0 pour aucune limite.');s.defaultDurationSec=n;s.showLeaderboard=!!body.showLeaderboard;s.speedBonusEnabled=!!body.speedBonusEnabled;}
      else if(action==='pause'){if(s.status==='active'&&!s.paused){s.paused=true;s.questionPausedAt=now();s.pauseRemainingMs=s.deadlineAt?Math.max(0,s.deadlineAt-now()):null;s.deadlineAt=null;}}
      else if(action==='resume'){if(s.status==='active'&&s.paused){s.paused=false;s.pausedDurationMs=(s.pausedDurationMs||0)+(s.questionPausedAt?now()-s.questionPausedAt:0);s.questionPausedAt=null;s.deadlineAt=s.pauseRemainingMs!=null?now()+s.pauseRemainingMs:null;s.pauseRemainingMs=null;}}
      else if(action==='lock')s.locked=true;
      else if(action==='unlock'){if(s.reveal)fail('Masque la correction avant de déverrouiller.',409);s.locked=false;}
      else if(action==='reveal'){if(s.status!=='active')fail('Démarre la session avant d’afficher une correction.',409);s.reveal=true;s.locked=true;}
      else if(action==='hideCorrection')s.reveal=false;
      else if(action==='next'){if(s.status!=='active')fail('Aucune question en cours.',409);s.phase='quiz';if(s.current<quizOf(s).questions.length-1){s.current++;open(s);}else{s.status='finished';s.reveal=false;s.locked=true;s.deadlineAt=null;}}
      else if(action==='prev'){if(s.status==='waiting')fail('Démarre d’abord la session.',409);s.status='active';s.phase='quiz';s.current=Math.max(0,s.current-1);open(s);}
      else if(action==='challenge'||action==='surprise'){if(!(action==='challenge'?quizOf(s).challenge:quizOf(s).surprise))fail('Cette activité est indisponible.');s.status='active';s.phase=action;open(s);}
      else if(action==='finish'){s.status='finished';s.reveal=false;s.locked=true;s.deadlineAt=null;}
      else fail('Action inconnue.');
      await save(s);return reply(await teacher(s));
    }catch(e){if(!e.status)console.error('Quiz API:',e.message);return reply({error:e.status?e.message:'Le serveur n’a pas pu enregistrer cette opération. Réessaie.'},e.status||503);}
  };
}
