const SB='https://gzdixxmcptlymzjmjqat.supabase.co';
const KEY='sb_publishable_EDzzTxbfJ4BUwnUWHvRGiA_ba90g4Lu';
const CORE=SB+'/functions/v1/mbn-campus';
const CC=SB+'/functions/v1/edulink-cc';
const titles=['Environnement numérique & organisation professionnelle','Word & Google Docs professionnels','Excel & Google Sheets — fondamentaux','Excel avancé, TCD & dashboards','PowerPoint, Google Slides & Canva','Google Workspace avancé','Microsoft 365, Teams & SharePoint','Soft Skills & collaboration de projet','Forms & collecte de données','Publipostage & génération de documents','Macros, Power Automate & Apps Script','IA générative & productivité responsable','Sécurité numérique, intégration & hackathon final'];
let state={session:null,data:null,page:'home',content:null,courseIndex:0,quiz:null,cc:null,preview:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),3500)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function token(){return state.session?.access_token||localStorage.getItem('edulink_access')}
async function auth(path,body){const r=await fetch(SB+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||'Connexion impossible.');return d}
async function api(body,cc=false){const r=await fetch(cc?CC:CORE,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token(),'Content-Type':'application/json'},body:JSON.stringify({...body,preview:state.preview})}),d=await r.json();if(r.status===401){logout();throw Error('Session expirée. Reconnectez-vous.')}if(!r.ok)throw Error(d.error||'Action impossible.');return d}
async function refresh(){state.data=await api({action:'bootstrap'});render()}
function saveSession(s){state.session=s;localStorage.setItem('edulink_access',s.access_token);if(s.refresh_token)localStorage.setItem('edulink_refresh',s.refresh_token)}
async function restore(){const access=localStorage.getItem('edulink_access');if(!access)return showLogin();state.session={access_token:access};try{await refresh()}catch(e){const ref=localStorage.getItem('edulink_refresh');if(ref)try{const s=await auth('/auth/v1/token?grant_type=refresh_token',{refresh_token:ref});saveSession(s);return refresh()}catch{}showLogin()}}
function logout(){localStorage.removeItem('edulink_access');localStorage.removeItem('edulink_refresh');state={session:null,data:null,page:'home',content:null,courseIndex:0,quiz:null,cc:null,preview:false};showLogin()}
function showLogin(){document.body.innerHTML=`<section class="login"><div class="login-hero"><span class="pill">MBN Global Education · Bachelor 3</span><h1>Edulink</h1><p>Votre parcours pédagogique, vos cours, vos devoirs, vos évaluations et vos compétences au même endroit.</p></div><div class="login-panel"><form class="auth-card" id="loginForm"><h2>Connexion</h2><p class="muted">Utilisez l’adresse inscrite par votre établissement.</p><div class="field"><label>Email</label><input name="email" type="email" autocomplete="email" required></div><div class="field"><label>Mot de passe</label><input name="password" type="password" autocomplete="current-password" minlength="8" required></div><button class="btn" type="submit">Se connecter</button><button class="btn ghost" type="button" id="magic">Recevoir un lien de connexion</button><hr style="border:0;border-top:1px solid #e2e8f0;margin:22px 0"><p class="muted">Première connexion après inscription par l’établissement ?</p><button class="btn secondary" type="button" id="signup">Créer mon compte étudiant</button><div id="authMsg"></div></form></div></section>`;
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const s=await auth('/auth/v1/token?grant_type=password',{email:f.get('email'),password:f.get('password')});saveSession(s);await refresh()}catch(err){$('#authMsg').innerHTML=`<p class="notice error">${esc(err.message)}</p>`}};
$('#magic').onclick=async()=>{const email=$('[name=email]').value;if(!email)return toast('Saisissez votre email.');try{await auth('/auth/v1/otp',{email,options:{emailRedirectTo:location.origin}});$('#authMsg').innerHTML='<p class="notice success">Lien de connexion envoyé si cette adresse est autorisée.</p>'}catch(e){$('#authMsg').innerHTML=`<p class="notice error">${esc(e.message)}</p>`}};
$('#signup').onclick=()=>signupView();}
function signupView(){$('.auth-card').innerHTML=`<h2>Créer mon compte</h2><p class="muted">Votre email doit avoir été inscrit par le responsable pédagogique.</p><form id="signupForm"><div class="field"><label>Nom affiché</label><input name="display_name" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Mot de passe</label><input name="password" type="password" minlength="8" required></div><button class="btn">Créer le compte</button><button type="button" class="btn ghost" onclick="showLogin()">Retour</button><div id="authMsg"></div></form>`;$('#signupForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const d=await auth('/auth/v1/signup',{email:f.get('email'),password:f.get('password'),data:{display_name:f.get('display_name')}});if(d.access_token){saveSession(d);await refresh()}else $('#authMsg').innerHTML='<p class="notice success">Compte créé. Confirmez votre adresse email, puis connectez-vous.</p>'}catch(err){$('#authMsg').innerHTML=`<p class="notice error">${esc(err.message)}</p>`}}}
function shell(){const teacher=state.data.teacher;return `<div class="app"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">E</div><div><b>Edulink</b><small>Bachelor 3</small></div></div><nav class="nav">${[['home','Accueil'],['roadmap','Mon parcours'],['courses','Mes cours'],['homework',teacher?'Travaux à corriger':'Mes devoirs'],['cc','Mes évaluations'],['results','Mes résultats'],['skills','Mes compétences'],['attendance','Présences / absences'],['agenda','Agenda'],['messages','Messagerie'],...(teacher?[['classes','Classes & étudiants']]:[]),['settings','Paramètres']].map(([id,l])=>`<button data-page="${id}" class="${state.page===id?'active':''}">${l}</button>`).join('')}</nav><div class="sidebar-footer"><b>${esc(state.data.user.display_name||state.data.user.email)}</b><small style="display:block;color:#94a3b8">${teacher?'Équipe pédagogique':'Étudiant'}</small><button class="btn ghost" id="logout">Déconnexion</button></div></aside><section class="main"><header class="topbar"><div><button class="btn secondary mobile-menu" id="menu">☰</button> <b>Edulink</b></div><div class="actions">${state.data.canTeach?`<button class="btn secondary" id="preview">${state.preview?'Vue responsable':'Tester en étudiant'}</button>`:''}<span class="status ${state.data.integrations.database?'green':'red'}">Supabase ${state.data.integrations.database?'connecté':'hors ligne'}</span></div></header><main class="content" id="view"></main></section></div>`}
function render(){if(!state.data)return showLogin();document.body.innerHTML=shell();$$('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.content=null;state.quiz=null;state.cc=null;render()});$('#logout').onclick=logout;$('#menu')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#preview')?.addEventListener('click',async()=>{state.preview=!state.preview;await refresh()});renderPage()}
function chapters(){return state.data.catalog.filter(x=>x.kind==='chapter').sort((a,b)=>(a.chapter||0)-(b.chapter||0))}
function ccList(){return state.data.catalog.filter(x=>x.kind==='cc')}
function records(kind){return state.data.records.filter(r=>!kind||r.kind===kind)}
function progressFor(id){const read=records('read').find(r=>r.payload.contentId===id)?.payload.pages?.length||0,quiz=records('quiz').find(r=>r.payload.contentId===id)?.payload?.current?.score,sub=records('submission').find(r=>r.payload.contentId===id);return {read,quiz,sub,done:quiz>=12&&!!sub}}
function renderPage(){const v=$('#view');const d=state.data;switch(state.page){case'home':return v.innerHTML=dashboard();case'roadmap':return v.innerHTML=roadmap();case'courses':return v.innerHTML=courseCards();case'homework':return v.innerHTML=homeworkPage();case'cc':return v.innerHTML=ccPage();case'results':return v.innerHTML=resultsPage();case'skills':return v.innerHTML=skillsPage();case'attendance':return v.innerHTML=attendancePage();case'agenda':return v.innerHTML=agendaPage();case'messages':return v.innerHTML=messagesPage();case'classes':v.innerHTML=classesPage();bindClasses();return;case'settings':return v.innerHTML=settingsPage();case'chapter':v.innerHTML=chapterPage();bindChapter();return;case'quiz':v.innerHTML=quizPage();bindQuiz();return;case'ccrun':v.innerHTML=ccRunPage();bindCC();return;case'grade':v.innerHTML=gradePage();bindGrade();return}bindGlobal()}
function dashboard(){const ch=chapters(),done=ch.filter(c=>progressFor(c.id).done).length,pct=Math.round(done/ch.length*100)||0,subs=records('submission'),quizzes=records('quiz');return `<section class="hero"><div><div class="eyebrow">APPRENDRE · PRATIQUER · PROGRESSER</div><h1>Bonjour ${esc((state.data.user.display_name||'').split(' ')[0])}</h1><p class="muted">${state.data.teacher?'Pilotez la progression de votre classe et les évaluations.':'Votre cockpit pédagogique Bachelor 3.'}</p><div class="actions"><button class="btn" onclick="go('roadmap')">Continuer mon parcours</button></div></div><div><div class="kpi">${pct}%</div><div class="muted">progression globale</div></div></section><div class="grid stats" style="margin-top:18px"><div class="card stat"><strong>${done}/13</strong><span>chapitres validés</span></div><div class="card stat"><strong>${quizzes.filter(r=>r.payload?.current?.score>=12).length}</strong><span>quiz réussis</span></div><div class="card stat"><strong>${subs.length}</strong><span>${state.data.teacher?'remises enregistrées':'devoirs remis'}</span></div><div class="card stat"><strong>${ccList().length}</strong><span>contrôles continus</span></div></div><div class="grid two" style="margin-top:18px"><section class="card"><h2>À faire</h2><div class="list">${ch.slice(0,5).map(c=>{const p=progressFor(c.id);return `<div class="row"><div><b>Chapitre ${c.chapter}</b><div class="muted">${esc(titles[c.chapter-1])}</div></div><span class="status ${p.done?'green':c.active?'blue':'orange'}">${p.done?'Validé':c.active?'En cours':'À venir'}</span></div>`}).join('')}</div></section><section class="card"><h2>${state.data.teacher?'Demande mon attention':'Derniers résultats'}</h2>${state.data.teacher?`<div class="list"><div class="row"><b>Travaux à corriger</b><span>${records('submission').filter(r=>!r.payload.grade).length}</span></div><div class="row"><b>Étudiants inscrits</b><span>${state.data.profiles.filter(p=>p.role==='student').length}</span></div><div class="row"><b>CC actifs</b><span>${ccList().filter(c=>c.active).length}</span></div></div>`:resultLines()}</section></div>`}
function roadmap(){return `<div class="eyebrow">PARCOURS B3</div><h1>Mon parcours</h1><p class="muted">13 chapitres, quatre contrôles continus et deux partiels.</p><div class="roadmap">${chapters().map((c,i)=>{const p=progressFor(c.id),cl=p.done?'done':c.active?'active':'locked';let extra='';if([2,5,8,11].includes(i)){const k=[2,5,8,11].indexOf(i);extra=`<div class="step"><div><b>Jalon · ${['CC1 S1','CC2 S1','CC1 S2','CC2 S2'][k]}</b><div class="muted">6 variantes équivalentes · /20</div></div><span class="status blue">Évaluation</span></div>`}return `<div class="step ${cl}"><div><b>Chapitre ${c.chapter} — ${esc(titles[c.chapter-1])}</b><div class="muted">${p.quiz!=null?'Quiz '+p.quiz+'/20 · ':''}${p.sub?'Devoir remis':'Devoir à réaliser'}</div></div><div class="actions"><span class="status ${p.done?'green':c.active?'blue':'orange'}">${p.done?'Terminé':c.active?'Disponible':'À venir'}</span><button class="btn secondary" onclick="openChapter('${c.id}')">Ouvrir</button></div></div>${extra}`}).join('')}</div>`}
function courseCards(){return `<div class="eyebrow">COURS</div><h1>Mes cours</h1><div class="grid three">${chapters().map(c=>`<section class="card"><div class="eyebrow">CHAPITRE ${String(c.chapter).padStart(2,'0')}</div><h3>${esc(titles[c.chapter-1])}</h3><p class="muted">${c.questions||0} questions préparées · 1 devoir pratique</p><button class="btn" onclick="openChapter('${c.id}')">Ouvrir le chapitre</button></section>`).join('')}</div>`}
async function openChapter(id){try{state.content=(await api({action:'getContent',id})).content;state.page='chapter';state.courseIndex=0;render()}catch(e){toast(e.message)}}
function chapterPage(){const p=state.content,s=p.course?.sections?.[state.courseIndex];if(!s)return '<p>Chargement…</p>';return `<div class="actions"><button class="btn secondary" onclick="go('courses')">← Cours</button></div><div class="eyebrow">CHAPITRE ${p.chapter}</div><h1>${esc(titles[p.chapter-1])}</h1><div class="tabs"><button class="active">Cours</button><button onclick="startQuiz('${p.id}')">Diagnostic</button><button onclick="document.getElementById('homeworkBox').scrollIntoView()">Devoir</button></div><div class="course-layout"><aside class="card course-nav">${p.course.sections.map((x,i)=>`<button class="${i===state.courseIndex?'active':''}" onclick="state.courseIndex=${i};render()">${x.page}. ${esc(x.title)}</button>`).join('')}</aside><article><section class="card"><div class="eyebrow">SECTION ${s.page}</div><h2>${esc(s.title)}</h2><div class="course-text">${esc(s.text)}</div><div class="actions"><button class="btn secondary" ${state.courseIndex===0?'disabled':''} onclick="state.courseIndex--;render()">Précédent</button><button class="btn secondary" onclick="markRead('${p.id}',${s.page})">Marquer comme lu</button><button class="btn" ${state.courseIndex===p.course.sections.length-1?'disabled':''} onclick="state.courseIndex++;render()">Suivant</button></div></section><section class="card" id="homeworkBox" style="margin-top:18px"><h2>${esc(p.assignment.title)}</h2><p>${esc(p.assignment.context)}</p><p class="muted">${p.assignment.minutes||''} minutes · barème /20</p><form onsubmit="submitHomework(event,'${p.id}')"><div class="field"><label>Réponse / justification</label><textarea name="text" rows="7"></textarea></div><div class="field"><label>Lien de partage HTTPS</label><input name="link" type="url"></div><div class="field"><label>Fichier</label><input name="file" type="file" accept=".pdf,.docx,.xlsx,.pptx,.zip,.txt,.csv,.json,.png,.jpg,.jpeg"></div><button class="btn">Remettre mon travail</button></form></section></article></div>`}
async function markRead(id,page){try{await api({action:'markRead',contentId:id,page});toast('Lecture enregistrée.');await refresh()}catch(e){toast(e.message)}}
async function startQuiz(id){try{state.quiz=(await api({action:'startQuiz',contentId:id})).attempt;state.page='quiz';render()}catch(e){toast(e.message)}}
function quizPage(){const a=state.quiz?.current;if(!a)return '<p>Aucune tentative.</p>';const submitted=a.status==='SUBMITTED';return `<div class="eyebrow">DIAGNOSTIC</div><h1>${submitted?'Résultat : '+a.score+'/20':'Quiz · 10 questions'}</h1>${a.questions.map((q,i)=>`<section class="card" style="margin-bottom:12px"><div class="eyebrow">QUESTION ${i+1} · ${q.difficulty}</div><h3>${esc(q.prompt)}</h3>${q.options.map((o,j)=>`<label class="quiz-option"><input type="radio" name="${q.id}" value="${j}" ${a.answers?.[q.id]===j?'checked':''} ${submitted?'disabled':''}> <span>${esc(o)}</span></label>`).join('')}${submitted?`<p class="notice ${a.feedback?.[i]?.answer===a.answers?.[q.id]?'success':'error'}">${esc(a.feedback?.[i]?.explanation||'')}</p>`:''}</section>`).join('')}<div class="actions">${submitted?`<button class="btn" onclick="startQuiz('${state.quiz.id.split(':').pop()}')">Nouvelle tentative</button>`:`<button class="btn" onclick="saveQuiz(false)">Enregistrer</button><button class="btn" onclick="saveQuiz(true)">Terminer</button>`}</div>`}
async function saveQuiz(final){const answers={};state.quiz.current.questions.forEach(q=>{const x=document.querySelector(`input[name="${q.id}"]:checked`);if(x)answers[q.id]=Number(x.value)});try{const r=await api({action:final?'submitQuiz':'saveQuiz',contentId:state.quiz.id.split(':').pop(),version:state.quiz.version,answers});state.quiz=r.attempt;render()}catch(e){toast(e.message)}}
async function uploadFile(file){if(!file)return null;const base64=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)});return (await api({action:'upload',name:file.name,base64})).file.id}
async function submitHomework(e,id){e.preventDefault();const f=new FormData(e.currentTarget);try{const file=await uploadFile(f.get('file')?.size?f.get('file'):null),links=f.get('link')?[f.get('link')]:[];await api({action:'submitHomework',contentId:id,requestId:crypto.randomUUID(),deliverable:{text:f.get('text')||'',links,files:file?[file]:[]}});toast('Devoir remis.');await refresh()}catch(err){toast(err.message)}}
function homeworkPage(){const rs=records('submission');if(state.data.teacher)return `<h1>Travaux à corriger</h1>${rs.length?rs.map(r=>`<section class="card" style="margin-bottom:12px"><div class="row"><div><b>${esc(r.payload.student||r.actor)}</b><div class="muted">${esc(r.payload.contentId)}</div></div><div class="actions"><span class="status ${r.payload.grade?'green':'orange'}">${r.payload.grade?r.payload.grade.total+'/20':'À corriger'}</span><button class="btn" onclick="openGrade('${r.id}')">Corriger</button></div></div></section>`).join(''):'<div class="notice">Aucune remise.</div>'}`;return `<h1>Mes devoirs</h1>${rs.length?rs.map(r=>`<section class="card"><b>${esc(r.payload.contentId)}</b><span class="status green" style="float:right">${r.payload.grade?r.payload.grade.total+'/20':'Remis'}</span></section>`).join(''):'<div class="notice">Aucun devoir remis.</div>'}`}
async function openGrade(id){try{state.grade=(await api({action:'getRecord',id},true)).record;state.page='grade';render()}catch(e){toast(e.message)}}
function gradePage(){const r=state.grade,items=r.kind==='submission'?r.payload.assignment.rubric:r.payload.questions.map(q=>({id:q.id,title:q.prompt,max:q.points}));return `<h1>Correction</h1><section class="card"><p><b>${esc(r.payload.student||r.actor)}</b> · ${esc(r.payload.contentId)}</p>${r.payload.deliverable?`<div class="notice">${esc(r.payload.deliverable.text||'')}</div>`:''}<form id="gradeForm">${items.map(x=>`<div class="field"><label>${esc(x.title)} — /${x.max}</label><input name="${x.id}" type="number" min="0" max="${x.max}" step="0.25" required></div>`).join('')}<div class="field"><label>Appréciation</label><textarea name="comment" required></textarea></div><button class="btn">Enregistrer la note</button></form></section>`}
function bindGrade(){$('#gradeForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=state.grade,items=r.kind==='submission'?r.payload.assignment.rubric:r.payload.questions.map(q=>({id:q.id,max:q.points})),points={};items.forEach(x=>points[x.id]=Number(f.get(x.id)));try{await api({action:'grade',id:r.id,version:r.version,points,comment:f.get('comment')},true);toast('Correction enregistrée.');state.page='homework';await refresh()}catch(err){toast(err.message)}}}
function ccPage(){return `<div class="eyebrow">ÉVALUATIONS OFFICIELLES</div><h1>Mes contrôles continus</h1><div class="grid two">${ccList().map(c=>`<section class="card"><h2>${esc(c.id.replaceAll('-',' '))}</h2><p>6 variantes A–F · /20 · 120 minutes</p><span class="status ${c.active?'green':'orange'}">${c.active?'Activé':'Non ouvert'}</span><div style="margin-top:16px"><button class="btn" ${!c.active&&!state.preview?'disabled':''} onclick="startCC('${c.id}')">Commencer / reprendre</button></div></section>`).join('')}</div>`}
async function startCC(id){try{state.cc=(await api({action:'startCC',contentId:id},true)).attempt;state.page='ccrun';render()}catch(e){toast(e.message)}}
function ccRunPage(){const a=state.cc;if(!a)return'<p>Chargement…</p>';if(a.status!=='IN_PROGRESS')return `<section class="card"><h1>CC remis</h1><p>Variante ${esc(a.letter)}. Votre copie est enregistrée.</p></section>`;const q=a.current,sec=Math.max(0,Math.ceil((Date.parse(a.deadline)-Date.now())/1000));return `<div class="eyebrow">${esc(a.letter)} · EXERCICE ${a.index+1}/${a.count}</div><div class="row"><h1>Contrôle continu</h1><div class="timer" id="timer">${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}</div></div><section class="card"><h2>${esc(q.prompt)}</h2><p>${esc(q.deliverable||'')}</p><form id="ccForm"><div class="field"><label>Réponse</label><textarea name="text" rows="9">${esc(a.answer?.text||'')}</textarea></div><div class="field"><label>Lien HTTPS</label><input type="url" name="link" value="${esc(a.answer?.links?.[0]||'')}"></div><button class="btn secondary" type="button" id="saveCC">Enregistrer</button> <button class="btn" type="submit">${a.index===a.count-1?'Terminer le CC':'Valider et continuer'}</button></form><p class="muted">Le chronomètre continue si vous quittez la page.</p></section>`}
function bindCC(){if(!state.cc||state.cc.status!=='IN_PROGRESS')return;const tick=setInterval(()=>{if(state.page!=='ccrun')return clearInterval(tick);const s=Math.max(0,Math.ceil((Date.parse(state.cc.deadline)-Date.now())/1000));if($('#timer'))$('#timer').textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`},1000);const answer=()=>{const f=new FormData($('#ccForm'));return{text:f.get('text')||'',links:f.get('link')?[f.get('link')]:[],files:[]}};$('#saveCC').onclick=async()=>{try{state.cc=(await api({action:'saveCC',contentId:state.cc.id.split(':').pop(),version:state.cc.version,questionId:state.cc.current.id,answer:answer()},true)).attempt;toast('Réponse enregistrée.');render()}catch(e){toast(e.message)}};$('#ccForm').onsubmit=async e=>{e.preventDefault();try{state.cc=(await api({action:'nextCC',contentId:state.cc.id.split(':').pop(),version:state.cc.version,questionId:state.cc.current.id,answer:answer()},true)).attempt;render()}catch(err){toast(err.message)}}}
function resultLines(){const q=records('quiz').slice(0,4);return q.length?q.map(r=>`<div class="row"><div><b>${esc(r.payload.contentId||'Quiz')}</b></div><span class="status ${(r.payload.current?.score||0)>=12?'green':'orange'}">${r.payload.current?.score??'—'}/20</span></div>`).join(''):'<p class="muted">Aucun résultat pour le moment.</p>'}
function resultsPage(){const qs=records('quiz'),ss=records('submission'),cs=records('cc');return `<h1>Mes résultats</h1><div class="grid three"><section class="card"><h2>Quiz</h2>${qs.map(r=>`<div class="row"><span>${esc(r.payload.contentId||'Quiz')}</span><b>${r.payload.current?.score??'—'}/20</b></div>`).join('')||'<p class="muted">Aucun.</p>'}</section><section class="card"><h2>Devoirs</h2>${ss.map(r=>`<div class="row"><span>${esc(r.payload.contentId)}</span><b>${r.payload.grade?.total??'—'}/20</b></div>`).join('')||'<p class="muted">Aucun.</p>'}</section><section class="card"><h2>CC</h2>${cs.map(r=>`<div class="row"><span>${esc(r.payload.contentId)}</span><b>${r.payload.grade?.total??'—'}/20</b></div>`).join('')||'<p class="muted">Aucun.</p>'}</section></div>`}
function skillsPage(){return `<h1>Mes compétences</h1><div class="grid two">${chapters().slice(0,8).map((c,i)=>{const p=progressFor(c.id),n=p.done?100:p.quiz>=12?70:p.read?40:10;return `<section class="card"><b>${esc(titles[c.chapter-1])}</b><p class="muted">Progression estimée à partir des activités réalisées</p><div class="progress"><span style="width:${n}%"></span></div><p>${n}%</p></section>`}).join('')}</div>`}
function attendancePage(){const rs=records('attendance');return `<h1>Présences / absences</h1>${rs.length?rs.map(r=>`<section class="card"><div class="row"><b>${esc(r.payload.session||'Séance')}</b><span class="status ${r.payload.status==='PRESENT'?'green':r.payload.status==='LATE'?'orange':'red'}">${esc(r.payload.status)}</span></div></section>`).join(''):'<div class="notice">Aucune donnée de présence enregistrée.</div>'}`}
function agendaPage(){const rs=records('agenda');return `<h1>Agenda</h1>${rs.length?rs.map(r=>`<section class="card"><h3>${esc(r.payload.title||'Événement')}</h3><p>${esc(r.payload.date||'')}</p><p class="muted">${esc(r.payload.description||'')}</p></section>`).join(''):'<div class="notice">Aucune échéance enregistrée.</div>'}`}
function messagesPage(){const rs=records('message');return `<h1>Messagerie</h1><section class="card"><form id="msgForm"><div class="field"><label>Message à l’équipe pédagogique</label><textarea name="text" required></textarea></div><button class="btn">Envoyer</button></form></section>${rs.map(r=>`<section class="card"><p>${esc(r.payload.text)}</p></section>`).join('')}`}
function classesPage(){return `<h1>Classes & étudiants</h1><div class="grid two"><section class="card"><h2>Créer une classe</h2><form id="classForm"><div class="field"><label>Nom</label><input name="name" required></div><button class="btn">Créer</button></form></section><section class="card"><h2>Inscrire un étudiant</h2><form id="enrollForm"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Classe</label><select name="classId">${state.data.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><button class="btn">Inscrire</button></form></section></div><section class="card" style="margin-top:18px"><h2>Étudiants</h2><div class="table-wrap"><table><thead><tr><th>Nom</th><th>Email</th><th>Rôle</th></tr></thead><tbody>${state.data.profiles.map(p=>`<tr><td>${esc(p.display_name)}</td><td>${esc(p.email)}</td><td>${esc(p.role)}</td></tr>`).join('')}</tbody></table></div></section>`}
function bindClasses(){$('#classForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api({action:'createClass',name:f.get('name')});toast('Classe créée.');await refresh()}catch(x){toast(x.message)}};$('#enrollForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api({action:'enroll',email:f.get('email'),classId:f.get('classId'),role:'student'});toast('Inscription enregistrée.');await refresh()}catch(x){toast(x.message)}}}
function settingsPage(){const i=state.data.integrations;return `<h1>Paramètres</h1><section class="card"><h2>Connexions</h2>${[['Base de données',i.database],['Stockage privé',i.storage],['Google Classroom',i.googleClassroom],['Emails automatiques',i.email],['Régénération IA',i.aiRegeneration]].map(([n,ok])=>`<div class="row"><b>${n}</b><span class="status ${ok?'green':'orange'}">${ok?'Connecté':'À configurer'}</span></div>`).join('')}</section><section class="card" style="margin-top:18px"><h2>Sécurité</h2><p class="muted">Les banques de questions et corrigés restent côté serveur. Les étudiants ne reçoivent que les éléments nécessaires à leur tentative.</p></section>`}
function bindChapter(){}function bindQuiz(){}function bindGlobal(){}
function go(p){state.page=p;render()}
window.state=state;window.go=go;window.openChapter=openChapter;window.startQuiz=startQuiz;window.markRead=markRead;window.submitHomework=submitHomework;window.saveQuiz=saveQuiz;window.startCC=startCC;window.openGrade=openGrade;window.showLogin=showLogin;
restore();