import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from '../src/live-core.mjs';
import {convertRows,parseCSV,suggestedMap} from '../public/assets/importer.js';
function harness(pin='test-teacher'){
 const data=new Map(),etags=new Map(),db={get:async k=>data.has(k)?structuredClone(data.get(k)):null,getWithMetadata:async k=>data.has(k)?{data:structuredClone(data.get(k)),etag:String(etags.get(k)||1),metadata:{}}:null,setJSON:async(k,v,options={})=>{if(options.onlyIfNew&&data.has(k)||options.onlyIfMatch&&options.onlyIfMatch!==String(etags.get(k)||1))return {modified:false};data.set(k,structuredClone(v));const revision=(etags.get(k)||1)+1;etags.set(k,revision);return {modified:true,etag:String(revision)};},list:async({prefix})=>({blobs:[...data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))})};
 const handler=createHandler({getStore:()=>db,teacherPin:()=>pin});
 const call=async(action,body=null,{teacher=true,session='',id=''}={})=>{const url=new URL('https://quiz.test/api/live');url.searchParams.set('action',action);if(session)url.searchParams.set('session',session);if(id)url.searchParams.set('id',id);const res=await handler(new Request(url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(teacher?{'x-teacher-pin':'test-teacher'}:{})},body:body?JSON.stringify(body):undefined}));return {status:res.status,data:await res.json()};};
 return {call,data,handler};
}
const sample=()=>({title:'Import Excel',classId:'m2-marketing',questions:[{question:'Quel objectif est mesurable ?',options:['Plus de visibilité','100 inscriptions'],correct:1,theme:'SMART'},{question:'Choisissez les canaux payants',type:'multi',options:['SEO','Search Ads','Social Ads'],correct:[1,2],theme:'Acquisition'}]});
test('Classes et quiz existants ; accès enseignant fermé sans PIN',async()=>{const {call}=harness();assert.equal((await call('library',null,{teacher:false})).status,401);const l=(await call('library')).data;assert.equal(l.classes.length,3);assert.deepEqual(l.classes.find(x=>x.id==='b3-tronc-commun').courses,['Outils collaboratifs','Gestion de projet','Soft skills']);assert.deepEqual(l.quizzes.map(q=>q.id),['diagnostic','neofit']);assert.equal(l.quizzes[1].questionCount,12);const noSecret=harness(undefined);/* default args need explicit empty config */const noSecretHandler=createHandler({getStore:()=>({}),teacherPin:()=>undefined});assert.equal((await noSecretHandler(new Request('https://quiz.test/api/live?action=library'))).status,503);});
test('Créer et modifier une classe ; éviter doublons et écritures périmées',async()=>{const {call}=harness();const c=(await call('saveClass',{classData:{name:'M1 Communication',courses:['Stratégie','Stratégie']}})).data;assert.equal(c.revision,1);assert.deepEqual(c.courses,['Stratégie']);assert.equal((await call('saveClass',{classData:{name:c.name}})).status,400);assert.equal((await call('saveClass',{classData:{...c,name:'M1 — groupe A'}})).status,200);assert.equal((await call('saveClass',{classData:{...c,name:'Ancien nom'}})).status,409);});
test('Importer CSV, plusieurs réponses, bonnes réponses manquantes et labels invalides',()=>{const rows=parseCSV('\uFEFFQuestion;Choix A;Choix B;Choix C;Bonne(s) réponse(s);Thème;Explication\r\n"Le CPL ; comment ?";Budget/leads;Leads/budget;;A;CPL;"Calcul sur\ndeux lignes"\nLeviers;SEO;SEA;Social Ads;B;Acquisition;Payant\nMultiple;A1;B1;C1;A;Concept;\nSans corrigé;Oui;Non;;;;\nErreur;Oui;Non;;Z;;');const map=suggestedMap(rows[0]);assert.equal(map.correct,4);const r=convertRows(rows,0,map);assert.equal(r.questions.length,5);assert.equal(r.questions[0].correct,0);assert.match(r.questions[0].explanation,/deux lignes/);assert.equal(r.questions[3].correct,null);assert.equal(r.questions[4].correct,null);const multi=convertRows([rows[0],['Deux canaux','SEO','SEA','Social Ads','B;C','Acquisition','']],0,map);assert.deepEqual(multi.questions[0].correct,[1,2]);assert.equal(multi.questions[0].type,'multi');assert.throws(()=>parseCSV('Question;A\n"broken'),/guillemets/);assert.throws(()=>convertRows(rows,0,{...map,B:map.A}),/deux champs/);});
test('Un quiz incomplet reste en brouillon et ne peut pas être lancé',async()=>{const {call}=harness(),q=sample();q.questions[0].correct=null;let r=await call('saveQuiz',{quiz:q});assert.equal(r.status,200);assert.equal(r.data.status,'draft');assert.equal((await call('createSession',{quizId:r.data.id})).status,400);r.data.questions[0].correct=1;r=await call('saveQuiz',{quiz:r.data});assert.equal(r.data.status,'ready');assert.equal((await call('createSession',{quizId:r.data.id})).status,200);assert.equal((await call('saveQuiz',{quiz:{id:'diagnostic',title:'Oops',questions:q.questions}})).status,400);});
test('Sessions simultanées, réponses concurrentes, corrections protégées et historique',async()=>{const {call}=harness(),q=(await call('saveQuiz',{quiz:sample()})).data;const a=(await call('createSession',{quizId:q.id,classId:'m2-marketing'})).data,b=(await call('createSession',{quizId:q.id,classId:'b3-cdui'})).data;assert.notEqual(a.sessionCode,b.sessionCode);const session=a.sessionCode;assert.equal((await call('state',null,{session:'WRONG1',teacher:false})).status,404);const joins=await Promise.all(Array.from({length:24},(_,i)=>call('join',{name:'Étudiant '+i},{session,teacher:false})));const ids=joins.map(x=>x.data.id);assert.equal(new Set(ids).size,24);assert.equal((await call('answer',{id:ids[0],key:'q0',answer:1},{session,teacher:false})).status,409);await call('settings',{defaultDurationSec:60},{session});await call('start',{}, {session});const pub=(await call('state',null,{session,teacher:false})).data;assert.equal(pub.question.correct,undefined);assert.equal(pub.question.explanation,undefined);assert.equal((await call('student',null,{session,id:ids[0],teacher:false})).data.score,null);const answers=await Promise.all(ids.map(id=>call('answer',{id,key:'q0',answer:1},{session,teacher:false})));assert.ok(answers.every(r=>r.status===200));assert.equal((await call('teacher',null,{session})).data.currentMetric.responses,24);assert.equal((await call('teacher',null,{session:b.sessionCode})).data.participantCount,0);assert.equal((await call('answer',{id:ids[0],key:'q0',answer:0},{session,teacher:false})).status,409);assert.equal((await call('answer',{id:ids[0],key:'q0',answer:null},{session,teacher:false})).status,400);await call('pause',{}, {session});assert.equal((await call('state',null,{session,teacher:false})).data.paused,true);await call('resume',{}, {session});await call('reveal',{}, {session});assert.equal((await call('state',null,{session,teacher:false})).data.question.correct,1);await call('next',{}, {session});assert.equal((await call('state',null,{session,teacher:false})).data.question.correct,undefined);await call('answer',{id:ids[0],key:'q1',answer:[2,1]}, {session,teacher:false});await call('answer',{id:ids[1],key:'q1',answer:[1]}, {session,teacher:false});await call('finish',{}, {session});const good=(await call('student',null,{session,id:ids[0],teacher:false})).data,bad=(await call('student',null,{session,id:ids[1],teacher:false})).data;assert.equal(good.score.percent,100);assert.equal(bad.score.percent,50);const library=(await call('library')).data;assert.equal(library.sessions.length,2);assert.equal(library.sessions.find(s=>s.sessionCode===session).participantCount,24);});
test('Modifier un quiz après lancement ne change pas le corrigé de sa session',async()=>{const {call}=harness();let q=(await call('saveQuiz',{quiz:sample()})).data;const s=(await call('createSession',{quizId:q.id})).data;q.questions[0].correct=0;q=(await call('saveQuiz',{quiz:q})).data;assert.equal((await call('teacher',null,{session:s.sessionCode})).data.quizFull.questions[0].correct,1);const b=(await call('createSession',{quizId:q.id})).data;assert.equal(b.quizFull.questions[0].correct,0);q.revision--;assert.equal((await call('saveQuiz',{quiz:q})).status,409);});
test('Deux envois simultanés du même étudiant ne peuvent pas remplacer sa réponse',async()=>{const {call}=harness(),q=(await call('saveQuiz',{quiz:sample()})).data,s=(await call('createSession',{quizId:q.id})).data,session=s.sessionCode;const p=(await call('join',{name:'Même étudiant'},{session,teacher:false})).data;await call('start',{}, {session});const r=await Promise.all([call('answer',{id:p.id,key:'q0',answer:0},{session,teacher:false}),call('answer',{id:p.id,key:'q0',answer:1},{session,teacher:false})]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);assert.equal((await call('teacher',null,{session})).data.currentMetric.responses,1);});
test('Ancienne session NÉO FIT migrée, challenge et carte surprise conservés',async()=>{const {call,data}=harness();data.set('control',{quizId:'neofit',sessionCode:'OLD123',status:'waiting',phase:'quiz',current:0,version:1,createdAt:Date.now()});const t=(await call('teacher')).data;assert.equal(t.quiz.totalQuestions,12);assert.equal(t.quiz.hasChallenge,true);await call('start',{}, {session:'OLD123'});assert.equal((await call('challenge',{}, {session:'OLD123'})).data.phase,'challenge');assert.equal((await call('surprise',{}, {session:'OLD123'})).data.phase,'surprise');assert.equal((await call('state',null,{session:'OLD123',teacher:false})).data.question.correct,undefined);});
test('Deux onglets enregistrant le même quiz ou la même classe ne perdent pas leurs modifications',async()=>{const {call}=harness();const q=(await call('saveQuiz',{quiz:sample()})).data;const saves=await Promise.all([call('saveQuiz',{quiz:{...q,title:'Version A'}}),call('saveQuiz',{quiz:{...q,title:'Version B'}})]);assert.deepEqual(saves.map(x=>x.status).sort(),[200,409]);const c=(await call('saveClass',{classData:{name:'Classe multi-onglets',courses:[]}})).data;const classes=await Promise.all([call('saveClass',{classData:{...c,level:'A'}}),call('saveClass',{classData:{...c,level:'B'}})]);assert.deepEqual(classes.map(x=>x.status).sort(),[200,409]);});
test('Une pause conserve le chrono et ne pénalise pas le temps de réponse ni le bonus',async t=>{let clock=Date.now();t.mock.method(Date,'now',()=>clock);const {call}=harness();const q=(await call('saveQuiz',{quiz:sample()})).data,s=(await call('createSession',{quizId:q.id})).data,session=s.sessionCode;const p=(await call('join',{name:'Chrono'},{session,teacher:false})).data;await call('settings',{defaultDurationSec:60,speedBonusEnabled:true},{session});await call('start',{}, {session});clock+=1500;await call('pause',{}, {session});clock+=120000;assert.equal((await call('answer',{id:p.id,key:'q0',answer:1},{session,teacher:false})).status,409);await call('resume',{}, {session});clock+=500;assert.equal((await call('state',null,{session,teacher:false})).data.remainingSec,58);await call('answer',{id:p.id,key:'q0',answer:1},{session,teacher:false});const teacher=(await call('teacher',null,{session})).data;assert.equal(teacher.currentMetric.avgResponseSec,2);assert.ok(teacher.participants[0].bonus>230);});
